name: 3D Contribution Graph
on:
  schedule:
    - cron: "0 18 * * *"  # 15h horário de Brasília
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate 3D chart
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          target_file: "dist/profile-3d.svg"  # Agora na pasta dist/

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/profile-3d.svg
          git commit -m "Update 3D contribution graph"
          git push
